# Generated by Django 5.1.7 on 2025-03-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skin',
            name='labeled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skin',
            name='labels',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
