# Generated by Django 5.1.7 on 2025-03-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_alter_skin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='name',
            field=models.CharField(max_length=1000),
        ),
    ]
