# Generated by Django 5.1.7 on 2025-07-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0002_skin_description_skin_labeled_at_skin_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.URLField(blank=True, default='https://bonkleagues.io/api/avatar.svg?skinCode=CgcDYQACCQkBCgcFYWwAAQBNPlt5PUI19d8%2FGMUDPsJvGgAAAAAAAAoFAAEATT5beT1CNfXfvvn8kL80i70BAAAAAAAKBQABAEs%2BgkonQjVq%2FL2vivk9L4r5AAAAzxsPCgUAAQANP1yl2D9VbKUAAAAAAAAAAAAAAM8bDwAAAAA%3D', max_length=4000, null=True),
        ),
    ]
