# Generated by Django 5.1.7 on 2025-03-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0003_alter_skin_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='creator',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
