# Generated by Django 5.1.7 on 2025-07-30 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0003_alter_skin_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='skin',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorite_skins', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='skin',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SkinVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('up', 'Upvote'), ('down', 'Downvote')], max_length=4)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skins.skin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'skin')},
            },
        ),
    ]
