# Generated by Django 5.1.7 on 2025-08-23 02:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0004_skin_downvotes_skin_favorited_by_skin_upvotes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonkPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonk_id', models.BigIntegerField(db_index=True, unique=True)),
                ('username', models.CharField(db_index=True, max_length=255)),
                ('last_seen', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_friend_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['bonk_id'], name='skins_bonkp_bonk_id_65d61a_idx'), models.Index(fields=['username'], name='skins_bonkp_usernam_420f86_idx')],
            },
        ),
        migrations.CreateModel(
            name='FriendCountHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_count_history', to='skins.bonkplayer')),
            ],
        ),
        migrations.CreateModel(
            name='BonkAccountLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_encrypted', models.TextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('scopes', models.JSONField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonk_accounts', to=settings.AUTH_USER_MODEL)),
                ('bonk_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_site_users', to='skins.bonkplayer')),
            ],
            options={
                'unique_together': {('user', 'bonk_player')},
            },
        ),
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_confirmed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('player_high', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_high', to='skins.bonkplayer')),
                ('player_low', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_low', to='skins.bonkplayer')),
            ],
            options={
                'indexes': [models.Index(fields=['player_low', 'player_high'], name='skins_frien_player__25ca38_idx'), models.Index(fields=['player_high', 'player_low'], name='skins_frien_player__7d8c94_idx')],
                'constraints': [models.UniqueConstraint(fields=('player_low', 'player_high'), name='uniq_undirected_friendship'), models.CheckConstraint(condition=models.Q(('player_low', models.F('player_high')), _negated=True), name='no_self_friendship')],
            },
        ),
    ]
