# Generated by Django 5.1.7 on 2025-03-22 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0004_alter_skin_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
