# Generated by Django 5.1.7 on 2025-08-24 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0005_bonkplayer_friendcounthistory_bonkaccountlink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlashFriend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bonk_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_flash_friend', to='skins.bonkplayer')),
            ],
            options={
                'unique_together': {('name', 'bonk_player')},
            },
        ),
        migrations.CreateModel(
            name='FlashFriendship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('flash_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_of', to='skins.flashfriend')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flash_friendships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'flash_friend')},
            },
        ),
    ]
