# Generated by Django 5.1.7 on 2025-08-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0006_flashfriend_flashfriendship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashfriend',
            name='name',
            field=models.TextField(db_index=True),
        ),
    ]
