# Generated by Django 5.1.7 on 2025-03-23 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0006_alter_skin_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.URLField(blank=True, max_length=4000, null=True),
        ),
    ]
