# Generated by Django 5.1.7 on 2025-03-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0007_alter_skin_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2024-03-22 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='skin',
            name='creator',
            field=models.CharField(blank=True, default='UnknownSkinCreator', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='skin',
            name='image_url',
            field=models.URLField(blank=True, default='https://bonkleaguebot.herokuapp.com/avatar.svg?skinCode=CgcDYQACCQkBCgcFYWwAAQBNPlt5PUI19d8%2FGMUDPsJvGgAAAAAAAAoFAAEATT5beT1CNfXfvvn8kL80i70BAAAAAAAKBQABAEs%2BgkonQjVq%2FL2vivk9L4r5AAAAzxsPCgUAAQANP1yl2D9VbKUAAAAAAAAAAAAAAM8bDwAAAAA%3D', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='skin',
            name='name',
            field=models.CharField(default='UnnamedSkin', max_length=1000),
        ),
    ]
