# Generated by Django 5.1.7 on 2025-09-10 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0008_changelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='original', max_length=50)),
                ('path', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skins.skin')),
            ],
        ),
    ]
