# Generated by Django 5.1.2 on 2025-09-14 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0009_skinimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='uuid',
            field=models.UUIDField(blank=True, default=None, editable=False, null=True, unique=True),
        ),
    ]
