# Generated by Django 5.1.2 on 2025-09-14 06:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0010_skin_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
