# Generated by Django 5.1.2 on 2025-09-15 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0011_alter_skin_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='skin',
            name='skin_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
