# Generated by Django 5.1.2 on 2025-09-28 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0012_skin_skin_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerWin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
