# Generated by Django 5.1.2 on 2025-09-30 15:49

import skins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0014_playersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playersession',
            name='username',
            field=models.CharField(db_index=True, max_length=35, unique=True, validators=[skins.models.validate_username]),
        ),
        migrations.AlterField(
            model_name='playerwin',
            name='username',
            field=models.CharField(db_index=True, max_length=100, validators=[skins.models.validate_username]),
        ),
    ]
