# Generated by Django 5.1.2 on 2025-10-03 21:40

import skins.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0015_alter_playersession_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerLoss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=35, validators=[skins.models.validate_username])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='playerwin',
            name='username',
            field=models.CharField(db_index=True, max_length=35, validators=[skins.models.validate_username]),
        ),
    ]
