# Generated by Django 5.1.2 on 2025-12-12 09:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0016_playerloss_alter_playerwin_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscordTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('category', models.CharField(blank=True, default='', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='DiscordServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('guild_id', models.CharField(db_index=True, max_length=32, unique=True)),
                ('invite_code', models.CharField(db_index=True, max_length=32)),
                ('invite_url', models.URLField(max_length=512)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_hash', models.CharField(blank=True, default='', max_length=128)),
                ('splash_hash', models.CharField(blank=True, default='', max_length=128)),
                ('member_count', models.IntegerField(default=0)),
                ('online_count', models.IntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invite_expired', 'Invite Expired'), ('disabled', 'Disabled')], default='active', max_length=32)),
                ('last_fetched_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, to='skins.discordtag')),
            ],
        ),
        migrations.CreateModel(
            name='DiscordServerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('member_count', models.IntegerField()),
                ('online_count', models.IntegerField()),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='skins.discordserver')),
            ],
            options={
                'indexes': [models.Index(fields=['server', 'recorded_at'], name='skins_disco_server__cb589f_idx')],
            },
        ),
    ]
