# Generated by Django 5.1.2 on 2025-12-20 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0017_discordtag_discordserver_discordserversnapshot'),
    ]

    operations = [
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm",
            reverse_sql="DROP EXTENSION IF EXISTS pg_trgm",
        )
    ]
