# Generated by Django 5.1.2 on 2026-02-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0018_auto_20251220_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skin',
            name='link',
            field=models.URLField(blank=True, help_text='Legacy external source (e.g. Bonkleagues import)', null=True),
        ),
    ]
