# Generated by Django 5.1.2 on 2026-05-14 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0019_alter_skin_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('inappropriate', 'Inappropriate content'), ('stolen', 'Stolen / reposted without credit'), ('spam', 'Spam or low-effort'), ('broken', 'Broken / not loading'), ('other', 'Other')], max_length=32)),
                ('details', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skin_reports', to=settings.AUTH_USER_MODEL)),
                ('skin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='skins.skin')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('reporter__isnull', False)), fields=('skin', 'reporter'), name='one_report_per_user_per_skin')],
            },
        ),
    ]
