# Generated by Django 5.1.2 on 2026-06-02 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skins', '0020_skinreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonkuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
