# """
# Django settings for bonk_skin_search project.

# Generated by 'django-admin startproject' using Django 5.1.7.
# """

# from pathlib import Path
# import dj_database_url
# import os
# import logging
# from dotenv import load_dotenv
# from datetime import timezone as dt_timezone

# load_dotenv()

# # =========================================================
# # Environment
# # =========================================================

# ENV = os.getenv("ENV", "local")
# IS_PROD = ENV == "production"
# DEBUG = not IS_PROD

# SECRET_KEY = os.getenv("SECRET_KEY")

# if not SECRET_KEY:
#     if os.getenv("DJANGO_ALLOW_DUMMY_SECRET") == "true":
#         SECRET_KEY = "build-time-secret-key"
#     else:
#         raise RuntimeError("SECRET_KEY is not set")

# AUTH_USER_MODEL = "skins.BonkUser"

# # =========================================================
# # Base Directory
# # =========================================================

# BASE_DIR = Path(__file__).resolve().parent.parent

# # =========================================================
# # Static Files
# # =========================================================

# STATIC_URL = "/static/"

# STATICFILES_DIRS = [
#     BASE_DIR / "skins/static",
# ]

# STATIC_ROOT = BASE_DIR / "staticfiles"

# # WhiteNoise storage backend
# STORAGES = {
#     "staticfiles": {
#         "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
#     },
# }

# # =========================================================
# # Media Files
# # =========================================================

# MEDIA_URL = "/media/"

# MEDIA_ROOT = os.getenv(
#     "RAILWAY_VOLUME_MOUNT_PATH",
#     os.path.join(BASE_DIR, "media"),
# )

# # =========================================================
# # External Services
# # =========================================================

# BONKVERSE_EDITOR_URL = os.getenv(
#     "BONKVERSE_EDITOR_URL",
#     "http://localhost:5173",
# )

# BLSKIN_FETCHER_URL = os.getenv(
#     "BLSKIN_FETCHER_URL",
#     "https://blskinfetcher-production.up.railway.app/api/getSkin"
# )

# # =========================================================
# # Security / CORS
# # =========================================================

# CSRF_TRUSTED_ORIGINS = [
#     "http://127.0.0.1:8000",
#     "http://localhost:8000",
#     "https://bonkverse.io",
#     "https://www.bonkverse.io",
#     "https://bonk.io",
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     BONKVERSE_EDITOR_URL,
# ]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     BONKVERSE_EDITOR_URL,
# ]

# CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOW_HEADERS = [
#     "accept",
#     "authorization",
#     "content-type",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
# ]

# DEBUG_PROPAGATE_EXCEPTIONS = True

# if IS_PROD:
#     ALLOWED_HOSTS = [
#         "bonkverse-production.up.railway.app",
#         "bonkverse.io",
#         "www.bonkverse.io",
#         "127.0.0.1",
#         "localhost",
#     ]
# else:
#     ALLOWED_HOSTS = [
#         "bonkverse-production.up.railway.app",
#         "bonkverse.io",
#         "www.bonkverse.io",
#         "127.0.0.1",
#         "localhost",
#         "192.168.1.183",
#     ]

# # =========================================================
# # Installed Apps
# # =========================================================

# INSTALLED_APPS = [
#     # WhiteNoise
#     "whitenoise.runserver_nostatic",

#     # Django
#     "django.contrib.admin",
#     "django.contrib.auth",
#     "django.contrib.contenttypes",
#     "django.contrib.sessions",
#     "django.contrib.messages",
#     "django.contrib.staticfiles",

#     # Third-party
#     "django_extensions",
#     "django_ratelimit",
#     "django_celery_beat",
#     "corsheaders",

#     # Local apps
#     "skins",
# ]

# # =========================================================
# # Middleware
# # =========================================================

# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",

#     "django.middleware.security.SecurityMiddleware",

#     # WhiteNoise should come directly after SecurityMiddleware
#     "whitenoise.middleware.WhiteNoiseMiddleware",

#     "django.contrib.sessions.middleware.SessionMiddleware",
#     "django.middleware.common.CommonMiddleware",
#     "django.middleware.csrf.CsrfViewMiddleware",
#     "django.contrib.auth.middleware.AuthenticationMiddleware",
#     "django.contrib.messages.middleware.MessageMiddleware",
#     "django.middleware.clickjacking.XFrameOptionsMiddleware",
# ]

# # =========================================================
# # URL / Templates / WSGI
# # =========================================================

# ROOT_URLCONF = "bonk_skin_search.urls"

# TEMPLATES = [
#     {
#         "BACKEND": "django.template.backends.django.DjangoTemplates",
#         "DIRS": [BASE_DIR / "templates"],
#         "APP_DIRS": True,
#         "OPTIONS": {
#             "context_processors": [
#                 "django.template.context_processors.debug",
#                 "django.template.context_processors.request",
#                 "django.contrib.auth.context_processors.auth",
#                 "django.contrib.messages.context_processors.messages",
#                 "skins.context_processors.latest_update",
#                 "skins.context_processors.editor_urls",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = "bonk_skin_search.wsgi.application"

# # =========================================================
# # Database
# # =========================================================

# DATABASES = {
#     "default": dj_database_url.config(
#         default=os.getenv("DATABASE_URL")
#     )
# }

# # =========================================================
# # Password Validation
# # =========================================================

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
#     },
#     {
#         "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
#     },
# ]

# # =========================================================
# # Internationalization
# # =========================================================

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True
# USE_TZ = True

# # =========================================================
# # Railway Timezone Fix
# # =========================================================

# try:
#     from zoneinfo import ZoneInfo
#     ZoneInfo(TIME_ZONE)
# except Exception as e:
#     logging.warning(
#         f"ZoneInfo not found for {TIME_ZONE}: {e}. Using UTC fallback."
#     )

#     from django.utils import timezone as django_tz
#     django_tz.get_default_timezone = lambda: dt_timezone.utc

# # =========================================================
# # Default PK
# # =========================================================

# DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# # =========================================================
# # Redis / Cache
# # =========================================================

# REDIS_URL = os.getenv("REDIS_URL")

# print("Using REDIS_URL:", REDIS_URL)
# print("Current ENV:", ENV)

# if REDIS_URL:
#     CACHES = {
#         "default": {
#             "BACKEND": "django_redis.cache.RedisCache",
#             "LOCATION": REDIS_URL,
#             "OPTIONS": {
#                 "CLIENT_CLASS": "django_redis.client.DefaultClient",
#             },
#             "KEY_PREFIX": "bonkverse",
#         }
#     }
# else:
#     CACHES = {
#         "default": {
#             "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#             "LOCATION": "bonkverse-locmem",
#         }
#     }

# RATELIMIT_USE_CACHE = "default"

# # =========================================================
# # Celery
# # =========================================================

# CELERY_BROKER_URL = REDIS_URL
# CELERY_RESULT_BACKEND = REDIS_URL

# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"

# CELERY_TIMEZONE = TIME_ZONE
# CELERY_ENABLE_UTC = True

# """
# Django settings for bonk_skin_search project.

# Generated by 'django-admin startproject' using Django 5.1.7.

# For more information on this file, see
# https://docs.djangoproject.com/en/5.1/topics/settings/

# For the full list of settings and their values, see
# https://docs.djangoproject.com/en/5.1/ref/settings/
# """

# from pathlib import Path
# import dj_database_url
# import os
# from dotenv import load_dotenv
# load_dotenv()

# ENV = os.getenv("ENV", "local")
# IS_PROD = ENV == "production"
# DEBUG = not IS_PROD

# SECRET_KEY = os.getenv("SECRET_KEY")

# if not SECRET_KEY:
#     if os.getenv("DJANGO_ALLOW_DUMMY_SECRET") == "true":
#         SECRET_KEY = "build-time-secret-key"
#     else:
#         raise RuntimeError("SECRET_KEY is not set")



# AUTH_USER_MODEL = 'skins.BonkUser'

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent

# STATIC_URL = "/static/"
# STATICFILES_DIRS = [os.path.join(BASE_DIR, "skins/static")]
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")

# BONKVERSE_EDITOR_URL = os.getenv(
#     "BONKVERSE_EDITOR_URL",
#     "http://localhost:5173",
# )

# BLSKIN_FETCHER_URL = os.getenv("BLSKIN_FETCHER_URL", "https://blskinfetcher-production.up.railway.app/api/getSkin")

# CSRF_TRUSTED_ORIGINS = [
#     "http://127.0.0.1:8000",
#     "http://localhost:8000",
#     "https://bonkverse.io",
#     "https://www.bonkverse.io",
#     "https://bonk.io",
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     BONKVERSE_EDITOR_URL,
# ]

# CORS_ALLOWED_ORIGINS = [
#     "http://localhost:5173",
#     "http://127.0.0.1:5173",
#     BONKVERSE_EDITOR_URL,
# ]

# CORS_ALLOW_CREDENTIALS = True

# CORS_ALLOW_HEADERS = [
#     "accept",
#     "authorization",
#     "content-type",
#     "user-agent",
#     "x-csrftoken",
#     "x-requested-with",
# ]


# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret
# # SECURITY WARNING: don't run with debug turned on in production!
# DEBUG_PROPAGATE_EXCEPTIONS = True

# if IS_PROD:
#     ALLOWED_HOSTS = ["bonkverse-production.up.railway.app", "bonkverse.io", "127.0.0.1", "localhost", "172.26.54.223", "http://localhost:5173", "http://127.0.0.1:5173"]
# else:
#     ALLOWED_HOSTS = ["bonkverse-production.up.railway.app", "bonkverse.io", "127.0.0.1", "localhost", "172.26.54.223", "http://localhost:5173", "http://127.0.0.1:5173", "192.168.1.183"]



# # Application definition

# INSTALLED_APPS = [
#     'django.contrib.admin',
#     'django.contrib.auth',
#     'django.contrib.contenttypes',
#     'django.contrib.sessions',
#     'django.contrib.messages',
#     'django.contrib.staticfiles',
#     'whitenoise.runserver_nostatic',  # Add this before Django's staticfiles
#     'skins',
#     'django_extensions',
#     'django_ratelimit',
#     "django_celery_beat",
#     "corsheaders",
# ]

# MIDDLEWARE = [
#     "corsheaders.middleware.CorsMiddleware",
#     'django.middleware.security.SecurityMiddleware',
#     'django.contrib.sessions.middleware.SessionMiddleware',
#     'django.middleware.common.CommonMiddleware',
#     'django.middleware.csrf.CsrfViewMiddleware',
#     'django.contrib.auth.middleware.AuthenticationMiddleware',
#     'django.contrib.messages.middleware.MessageMiddleware',
#     'django.middleware.clickjacking.XFrameOptionsMiddleware',
#     'whitenoise.middleware.WhiteNoiseMiddleware',
# ]

# ROOT_URLCONF = 'bonk_skin_search.urls'

# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [BASE_DIR / "templates"],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#                 'skins.context_processors.latest_update',
#                  "skins.context_processors.editor_urls",
#             ],
#         },
#     },
# ]

# WSGI_APPLICATION = 'bonk_skin_search.wsgi.application'


# # Database
# # https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': dj_database_url.config(default=os.getenv("DATABASE_URL"))
# }


# # Password validation
# # https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

# AUTH_PASSWORD_VALIDATORS = [
#     {
#         'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
#     },
#     {
#         'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
#     },
# ]


# # Internationalization
# # https://docs.djangoproject.com/en/5.1/topics/i18n/



# # Static files (CSS, JavaScript, Images)
# # https://docs.djangoproject.com/en/5.1/howto/static-files/


# # Default primary key field type
# # https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

# DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REDIS_URL = os.getenv("REDIS_URL")  # e.g. redis://127.0.0.1:6379/1 or rediss://...
# print("Using REDIS_URL:", REDIS_URL)
# print("The current environment is: ", ENV)


# if REDIS_URL:
#     CACHES = {
#         "default": {
#             "BACKEND": "django_redis.cache.RedisCache",
#             "LOCATION": REDIS_URL,
#             "OPTIONS": {
#                 "CLIENT_CLASS": "django_redis.client.DefaultClient",
#                 # "PASSWORD": os.getenv("REDIS_PASSWORD", ""),  # if your URL doesn’t embed it
#             },
#             "KEY_PREFIX": "bonkverse",
#         }
#     }
# else:
#     # Dev fallback: per-process in-memory cache
#     CACHES = {
#         "default": {
#             "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
#             "LOCATION": "bonkverse-locmem",
#         }
#     }

# # django-ratelimit should use the default cache
# RATELIMIT_USE_CACHE = "default"

# # Media files (go to volume in prod, ./media locally)
# MEDIA_URL = "/media/"

# # Use the Railway volume if it exists, else fall back to ./media
# MEDIA_ROOT = os.getenv("RAILWAY_VOLUME_MOUNT_PATH", os.path.join(BASE_DIR, "media"))

# LANGUAGE_CODE = 'en-us'

# TIME_ZONE = 'UTC'
# USE_I18N = True
# USE_TZ = True

# # ---- Fix missing timezone info in Railway ----
# # Some slim Linux containers (like Railway’s default) don’t include tzdata,
# # causing ZoneInfoNotFoundError: 'No time zone found with key UTC'
# import logging
# from datetime import timezone as dt_timezone

# try:
#     from zoneinfo import ZoneInfo
#     ZoneInfo(TIME_ZONE)
# except Exception as e:
#     logging.warning(f"ZoneInfo not found for {TIME_ZONE}: {e}. Using UTC fallback.")
#     from django.utils import timezone as django_tz
#     django_tz.get_default_timezone = lambda: dt_timezone.utc

# # --------------------
# # Celery configuration
# # --------------------

# CELERY_BROKER_URL = REDIS_URL
# CELERY_RESULT_BACKEND = REDIS_URL

# CELERY_ACCEPT_CONTENT = ["json"]
# CELERY_TASK_SERIALIZER = "json"
# CELERY_RESULT_SERIALIZER = "json"

# CELERY_TIMEZONE = TIME_ZONE
# CELERY_ENABLE_UTC = True
"""
Django settings for bonk_skin_search project.

Generated by 'django-admin startproject' using Django 5.1.7.
"""

from pathlib import Path
import dj_database_url
import os
import logging
from dotenv import load_dotenv
from datetime import timezone as dt_timezone

load_dotenv()

# =========================================================
# Environment
# =========================================================

ENV = os.getenv("ENV", "local")
IS_PROD = ENV == "production"
DEBUG = not IS_PROD

SECRET_KEY = os.getenv("SECRET_KEY")

if not SECRET_KEY:
    if os.getenv("DJANGO_ALLOW_DUMMY_SECRET") == "true":
        SECRET_KEY = "build-time-secret-key"
    else:
        raise RuntimeError("SECRET_KEY is not set")

AUTH_USER_MODEL = "skins.BonkUser"

# =========================================================
# Base Directory
# =========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# =========================================================
# Static Files
# =========================================================

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "skins/static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# WhiteNoise storage backend
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# =========================================================
# Media Files
# =========================================================

MEDIA_URL = "/media/"

MEDIA_ROOT = os.getenv(
    "RAILWAY_VOLUME_MOUNT_PATH",
    os.path.join(BASE_DIR, "media"),
)

# =========================================================
# External Services
# =========================================================

BONKVERSE_EDITOR_URL = os.getenv(
    "BONKVERSE_EDITOR_URL",
    "http://localhost:5173",
)

BLSKIN_FETCHER_URL = os.getenv(
    "BLSKIN_FETCHER_URL",
    "https://blskinfetcher-production.up.railway.app/api/getSkin"
)

BONKVERSE_BASE_URL = os.getenv("BONKVERSE_BASE_URL", "https://bonkverse.io")

CLOUDFLARE_ZONE_ID  = os.getenv("CLOUDFLARE_ZONE_ID", "")
CLOUDFLARE_CACHE_API_TOKEN = os.getenv("CLOUDFLARE_CACHE_API_TOKEN", "")

# =========================================================
# Security / CORS / Cookies
# =========================================================

# Prod: share session + CSRF cookies across *.bonkverse.io so editor.bonkverse.io
# is authenticated by the same login as bonkverse.io. Lax is sufficient because
# subdomains of one registrable domain are same-site.
if IS_PROD:
    SESSION_COOKIE_DOMAIN = ".bonkverse.io"
    CSRF_COOKIE_DOMAIN = ".bonkverse.io"
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"
else:
    # localhost:5173 ↔ localhost:8000: cookies are shared by host (port-agnostic),
    # so no domain needed; just don't require HTTPS.
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SAMESITE = "Lax"
    CSRF_COOKIE_SAMESITE = "Lax"

# Editor JS must read the CSRF cookie to echo it as X-CSRFToken → not HttpOnly.
CSRF_COOKIE_HTTPONLY = False

CSRF_TRUSTED_ORIGINS = [
    "https://bonkverse.io",
    "https://www.bonkverse.io",
    "https://editor.bonkverse.io",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOWED_ORIGINS = [
    "https://editor.bonkverse.io",
    "https://bonkverse.io",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "accept", "authorization", "content-type",
    "user-agent", "x-csrftoken", "x-requested-with",
]

# =========================================================
# Installed Apps
# =========================================================

INSTALLED_APPS = [
    # WhiteNoise
    "whitenoise.runserver_nostatic",

    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Third-party
    "django_extensions",
    "django_ratelimit",
    "django_celery_beat",
    "corsheaders",

    # Local apps
    "skins",
]

# =========================================================
# Middleware
# =========================================================

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",

    "django.middleware.security.SecurityMiddleware",

    # WhiteNoise should come directly after SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# =========================================================
# URL / Templates / WSGI
# =========================================================

ROOT_URLCONF = "bonk_skin_search.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "skins.context_processors.latest_update",
                "skins.context_processors.editor_urls",
            ],
        },
    },
]

WSGI_APPLICATION = "bonk_skin_search.wsgi.application"

# =========================================================
# Database
# =========================================================

DATABASES = {
    "default": dj_database_url.config(
        default=os.getenv("DATABASE_URL")
    )
}

# =========================================================
# Password Validation
# =========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# =========================================================
# Internationalization
# =========================================================

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True
USE_TZ = True

# =========================================================
# Railway Timezone Fix
# =========================================================

try:
    from zoneinfo import ZoneInfo
    ZoneInfo(TIME_ZONE)
except Exception as e:
    logging.warning(
        f"ZoneInfo not found for {TIME_ZONE}: {e}. Using UTC fallback."
    )

    from django.utils import timezone as django_tz
    django_tz.get_default_timezone = lambda: dt_timezone.utc

# =========================================================
# Default PK
# =========================================================

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# =========================================================
# Redis / Cache
# =========================================================

REDIS_URL = os.getenv("REDIS_URL")

print("Using REDIS_URL:", REDIS_URL)
print("Current ENV:", ENV)

if REDIS_URL:
    CACHES = {
        "default": {
            "BACKEND": "django_redis.cache.RedisCache",
            "LOCATION": REDIS_URL,
            "OPTIONS": {
                "CLIENT_CLASS": "django_redis.client.DefaultClient",
            },
            "KEY_PREFIX": "bonkverse",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "bonkverse-locmem",
        }
    }

RATELIMIT_USE_CACHE = "default"

# =========================================================
# Celery
# =========================================================

CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CELERY_TIMEZONE = TIME_ZONE
CELERY_ENABLE_UTC = True